### ISSUE TITLE
Fail validation

### ISSUE THREAD

**Issue by rmcgirr83** [GerB/simplerss#1]
Hi Ger,  This line

https://github.com/GerB/simplerss/blob/master/classes/driver.php#L45

will fail validation as they don't like people using serialize/unserialize.  Just an FYI.  config_text is big enough that you don't have to do that....I think.

**Comment by GerB** [comment]
Hi, Rich,
Thanks for noticing. Not sure why they don't like it though, it's just a matter of storing data efficiently. The phpBB core package does quite the same at some points.
But I see the EPV fails so I won't be able to get it validated. I could bypass this by using json_encode() or something like that bu I guess I'll just start a topic in the extension discussion forum instead.
