### ISSUE TITLE
 I want the RSS item list update and their posting on the forum to be triggered by the Linux 'cron' system service.

### ISSUE THREAD

**Issue by silosbc** [GerB/simplerss#11]
Hello GerB. Great job. I have a question: I would like to modify the way in which a list of new RSS items is periodically fetched in my forum. Specifically, I want the RSS item list update and their posting on the forum to be triggered by the Linux 'cron' system service. Can you provide me with instructions on how to do this? I am specifically interested in the command that I would need to enter in the configuration file of the 'cron' service, for example 'php /var/www/somesite.com/ext/ger/feedpostbot/somescript.php'.

**Comment by GerB** [comment]
https://www.phpbb.com/customise/db/extension/feedpostbot/support/topic/245446
