### ISSUE TITLE
BUG 3.2.2

### ISSUE THREAD

**Issue by flpsimu** [GerB/simplerss#2]
hi 

the cron job doesn't work with 3.2.2 update any issu ?

**Comment by GerB** [comment]
I have no issue with it but if you think there is a bug with cron jobs in phpBB in general, report to the phpBB bugtracker. If you think there is an issue with Feedpostbot in phpBB 3.2.2 report to extension topic on phpBB.com

**Comment by flpsimu** [comment]
My problem was related to errors in the translation file which prevented the cron.
Thank's good job
