### ISSUE TITLE
Allow feed category filtering

### ISSUE THREAD

**Issue by hexblot** [GerB/simplerss#4]
Hello,
would it be possible to have a simple text field and allow only feed items with a specific category name / pattern to be posted ? 

Alternatively, is there a way when implementing your events to deny posting an item? (To my understanding, when implementing ger.feedpostbot.parse_rss_append yuo can only massage the data, but cannot explicitly tell the module NOT to post an item)

Thank you in advance!

**Comment by GerB** [comment]
Usually you can add a filter to the feed itself, e.g. https://www.phpbb.com/community/feed/forum/616 to only show items within the 3.2.x extension releases. 

I haven't seen the need (and therefore haven't implemented anything) to filter after the fetching has been done.

What you could do is let the feeds post in a forum where topics are hidden by default and simply approve the items you like.

**Comment by GerB** [comment]
Closing as this won't be implemented and no reactions from TS.
Please seek support at phpBB.com.
