### ISSUE TITLE
Display problem

### ISSUE THREAD

**Issue by NecheB** [GerB/simplerss#8]
I have some problems with the display of the info in the post. Here are the pictures
[https://i.imgur.com/O5zDDKE.png](https://i.imgur.com/O5zDDKE.png)
[https://i.imgur.com/yDczeem.png](https://i.imgur.com/yDczeem.png)

ON the first image there is some problem with the code on the bottom. On the second all the info is together in one row. How that can be fixed to be like here
[https://i.imgur.com/qgaZfCT.png](https://i.imgur.com/qgaZfCT.png)

**Comment by GerB** [comment]
This looks like CLRF issues to me. Best you provide info at phpBB.com extension DB topic with provided feed URL
